version: '3.7'

services:
  db:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_DATABASE: 'maindb'
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
